use ofod;
CREATE TABLE `ofod_admin` (
  `ADMIN_ID` varchar(40) NOT NULL,
  `FIRST_NAME` varchar(20) DEFAULT NULL,
  `LAST_NAME` varchar(20) DEFAULT NULL,
  `USERNAME` varchar(20) DEFAULT NULL,
  `PASSWORD` varchar(500) DEFAULT NULL,
  `PHONE` varchar(14) DEFAULT NULL,
  `EMAIL` varchar(14) DEFAULT NULL,
  PRIMARY KEY (`ADMIN_ID`),
  UNIQUE KEY `ADMIN_ID` (`ADMIN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_caddress` (
  `ADDRESS_ID` varchar(40) NOT NULL,
  `CUSTOMER_ID` varchar(40) NOT NULL,
  `FIRST_NAME` varchar(25) DEFAULT NULL,
  `LAST_NAME` varchar(25) DEFAULT NULL,
  `ADDRESS1` varchar(20) DEFAULT NULL,
  `ADDRESS2` varchar(20) DEFAULT NULL,
  `CITY` varchar(20) DEFAULT NULL,
  `ZIPCODE` int(11) DEFAULT NULL,
  `PHONE` varchar(14) DEFAULT NULL,
  PRIMARY KEY (`ADDRESS_ID`,`CUSTOMER_ID`),
  KEY `FK_cust_addr_idx` (`CUSTOMER_ID`),
  CONSTRAINT `FK_cust_addr` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `ofod_customer` (`CUSTOMER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_coupon` (
  `COUPON_ID` varchar(40) NOT NULL,
  `COUPON_CODE` char(10) DEFAULT NULL,
  `COUPON_DESCRIPTION` varchar(20) DEFAULT NULL,
  `COUPON_TYPE` int(11) DEFAULT NULL,
  `COUPON_VALUE` int(11) DEFAULT NULL,
  `COUPON_VALIDITY` date DEFAULT NULL,
  PRIMARY KEY (`COUPON_ID`),
  UNIQUE KEY `Coupon_id` (`COUPON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_cuisine` (
  `CUISINE_ID` varchar(40) NOT NULL,
  `CUISINE_TYPE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CUISINE_ID`),
  UNIQUE KEY `Cuisine_id` (`CUISINE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_customer` (
  `CUSTOMER_ID` varchar(40) NOT NULL,
  `FIRST_NAME` varchar(20) NOT NULL,
  `LAST_NAME` varchar(20) DEFAULT NULL,
  `DOB` date NOT NULL,
  `PHONE` varchar(14) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `USERNAME` varchar(20) DEFAULT NULL,
  `PASSWORD` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  UNIQUE KEY `USERNAME_UNIQUE` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_driver` (
  `DRIVER_ID` varchar(40) NOT NULL,
  `FIRST_NAME` varchar(20) DEFAULT NULL,
  `LAST_NAME` varchar(20) DEFAULT NULL,
  `PHONE` varchar(14) DEFAULT NULL,
  `EMAIL` varchar(20) DEFAULT NULL,
  `VEHICLE_NO` varchar(20) NOT NULL,
  `LICENSE_NO` varchar(20) NOT NULL,
  PRIMARY KEY (`DRIVER_ID`),
  UNIQUE KEY `Driver_id` (`DRIVER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_item` (
  `ITEM_ID` varchar(40) NOT NULL,
  `RESTAURANT_ID` varchar(40) DEFAULT NULL,
  `ITEM_NAME` varchar(20) DEFAULT NULL,
  `ITEM_DESCRIPTION` varchar(20) DEFAULT NULL,
  `ITEM_PRICE` double(11,2) DEFAULT NULL,
  `ITEM_RATING` int(11) DEFAULT NULL,
  `FEEDBACK` varchar(50) DEFAULT NULL,
  `FEEDBACK_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ITEM_ID`),
  UNIQUE KEY `item_id` (`ITEM_ID`),
  KEY `ofod_item_ibfk_1` (`RESTAURANT_ID`),
  CONSTRAINT `ofod_item_ibfk_1` FOREIGN KEY (`RESTAURANT_ID`) REFERENCES `ofod_restaurant` (`RESTAURANT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_order` (
  `ORDER_ID` varchar(40) NOT NULL,
  `CUSTOMER_ID` varchar(40) NOT NULL,
  `CARD_ID` varchar(40) NOT NULL,
  `ADDRESS_ID` varchar(40) DEFAULT NULL,
  `TOTAL_PAYMENT` double(11,2) DEFAULT NULL,
  `TOTAL_RECEIVED` double(11,2) DEFAULT NULL,
  `ORDER_DATE` date DEFAULT NULL,
  `ORDER_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ORDER_STATUS` int(11) DEFAULT NULL,
  `DRIVER_ID` varchar(40) NOT NULL,
  `DELIVERY_MODE` int(11) DEFAULT NULL,
  `ORDER_FULFILMENT_TIME` timestamp  NULL,
  `ORDER_RATING` int(11) DEFAULT NULL,
  `ORDER_FEEDBACK` varchar(100) DEFAULT NULL,
  `FEEDBACK_TIME` timestamp  NULL ,
  PRIMARY KEY (`ORDER_ID`),
  UNIQUE KEY `ORDER_ID` (`ORDER_ID`),
  KEY `ORDER_FK1_idx` (`CUSTOMER_ID`),
  KEY `ORDER_FK2_idx` (`CARD_ID`),
  KEY `ORDER_FK3_idx` (`DRIVER_ID`),
  KEY `ORDER_FK3_idx1` (`CARD_ID`,`CUSTOMER_ID`),
  KEY `ORDER_FK3_idx2` (`ADDRESS_ID`),
  CONSTRAINT `ORDER_FK1` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `ofod_customer` (`CUSTOMER_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ORDER_FK2` FOREIGN KEY (`DRIVER_ID`) REFERENCES `ofod_driver` (`DRIVER_ID`),
  CONSTRAINT `ORDER_FK3` FOREIGN KEY (`ADDRESS_ID`) REFERENCES `ofod_caddress` (`ADDRESS_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_order_item` (
  `ORDER_ID` varchar(40) NOT NULL,
  `RESTAURANT_ID` varchar(40) NOT NULL,
  `COUPON_ID` varchar(40) NOT NULL,
  `ITEM_ID` varchar(40) NOT NULL,
  `ITEM_QUANTITY` int(11) DEFAULT NULL,
  PRIMARY KEY (`ORDER_ID`,`RESTAURANT_ID`,`ITEM_ID`),
  KEY `RESTAURANT_ID` (`RESTAURANT_ID`),
  KEY `COUPON_ID` (`COUPON_ID`),
  KEY `ITEM_ID` (`ITEM_ID`),
  CONSTRAINT `ofod_order_item_ibfk_1` FOREIGN KEY (`ORDER_ID`) REFERENCES `ofod_order` (`ORDER_ID`),
  CONSTRAINT `ofod_order_item_ibfk_2` FOREIGN KEY (`RESTAURANT_ID`) REFERENCES `ofod_restaurant` (`RESTAURANT_ID`),
  CONSTRAINT `ofod_order_item_ibfk_3` FOREIGN KEY (`COUPON_ID`) REFERENCES `ofod_coupon` (`COUPON_ID`),
  CONSTRAINT `ofod_order_item_ibfk_4` FOREIGN KEY (`ITEM_ID`) REFERENCES `ofod_item` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_payment` (
  `CUSTOMER_ID` varchar(40) NOT NULL,
  `CARD_ID` varchar(40) NOT NULL,
  `CARD_NO` bigint(16) NOT NULL,
  `EXPIRY` varchar(10) NOT NULL,
  `CARD_TYPE` varchar(10) NOT NULL,
  `NAME_ON_CARD` varchar(20) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`,`CARD_ID`),
  CONSTRAINT `ofod_payment_ibfk_1` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `ofod_customer` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_preferences` (
  `PREFERENCE_ID` varchar(40) NOT NULL,
  `CUISINE_ID` varchar(40) DEFAULT NULL,
  `RESTAURANT_ID` varchar(40) DEFAULT NULL,
  `CUSTOMER_ID` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`PREFERENCE_ID`),
  UNIQUE KEY `Preference_id` (`PREFERENCE_ID`),
  KEY `ofod_preferences_ibfk_1` (`CUISINE_ID`),
  KEY `ofod_preferences_ibfk_2` (`RESTAURANT_ID`),
  KEY `ofod_preferences_ibfk_3` (`CUSTOMER_ID`),
  CONSTRAINT `ofod_preferences_ibfk_1` FOREIGN KEY (`CUISINE_ID`) REFERENCES `ofod_cuisine` (`CUISINE_ID`),
  CONSTRAINT `ofod_preferences_ibfk_2` FOREIGN KEY (`RESTAURANT_ID`) REFERENCES `ofod_restaurant` (`RESTAURANT_ID`),
  CONSTRAINT `ofod_preferences_ibfk_3` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `ofod_customer` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_restaurant` (
  `RESTAURANT_ID` varchar(40) NOT NULL,
  `RESTAURANT_NAME` varchar(20) NOT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `ADDRESS1` varchar(20) DEFAULT NULL,
  `ADDRESS2` varchar(20) DEFAULT NULL,
  `CITY` varchar(20) DEFAULT NULL,
  `ZIPCODE` int(11) DEFAULT NULL,
  `PHONE` varchar(14) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `RATING` int(11) DEFAULT NULL,
  `FEEDBACK` varchar(50) DEFAULT NULL,
  `LATITUDE` double DEFAULT NULL,
  `LONGITUDE` double DEFAULT NULL,
  PRIMARY KEY (`RESTAURANT_ID`),
  UNIQUE KEY `restaurant_id` (`RESTAURANT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ofod_restaurantcuisine` (
  `CUISINE_ID` varchar(40) NOT NULL,
  `RESTAURANT_ID` varchar(40) NOT NULL,
  PRIMARY KEY (`CUISINE_ID`,`RESTAURANT_ID`),
  KEY `ofod_restaurantcuisine_ibfk_2` (`RESTAURANT_ID`),
  CONSTRAINT `ofod_restaurantcuisine_ibfk_1` FOREIGN KEY (`CUISINE_ID`) REFERENCES `ofod_cuisine` (`CUISINE_ID`),
  CONSTRAINT `ofod_restaurantcuisine_ibfk_2` FOREIGN KEY (`RESTAURANT_ID`) REFERENCES `ofod_restaurant` (`RESTAURANT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
